version: 2

updates:

  # Dependencias Java - Maven
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"

  # Imagenes Docker
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"